// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Programación_III.Data.Context;

#nullable disable

namespace TP_Programación_III.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220717045720_AddSaleToDB")]
    partial class AddSaleToDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("TP_Programación_III.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDiscount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Eukanuba Puppy es un producto ideal para mascotas menores al año de edad y entre 11 y 25 Kg. Considerado un alimento super premium, es de lo mejor que hay en el mercado",
                            HasDiscount = false,
                            Name = "Eukanuba Puppy x15",
                            Price = 14600,
                            ProductCategory = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Proplan Adult es un producto ideal para mascotas mayores al año y con un peso menor a 10 kg. Considerado un alimento super premium, es de lo mejor que hay en el mercado",
                            HasDiscount = false,
                            Name = "Proplan Adult x3",
                            Price = 4900,
                            ProductCategory = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Raza Adultos es un alimento masivo para perros adultos",
                            HasDiscount = true,
                            Name = "Raza Adult x20",
                            Price = 8100,
                            ProductCategory = 1
                        });
                });

            modelBuilder.Entity("TP_Programación_III.Entities.Sale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            ID = 4,
                            Name = "Vitalcan Complete x20",
                            PaymentType = 0,
                            Price = 9500,
                            ProductCategory = 1,
                            ShippingPlace = "Formosa"
                        });
                });

            modelBuilder.Entity("TP_Programación_III.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "pepito@email.com",
                            IsAdmin = false,
                            Name = "Pepito",
                            Password = "123456"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "juan@email.com",
                            IsAdmin = true,
                            Name = "Juan",
                            Password = "765432"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "carlos@email.com",
                            IsAdmin = false,
                            Name = "Carlos",
                            Password = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
